

POST http://localhost:3000/products HTTP/1.1
content-type: application/json

{
  "name": "Açucar",
  "description": "Açucar Camil 1kg",
  "price": 5.45,
  "purchasePrice": 3.45,
  "amount": 5
}


###
GET http://localhost:3000/products HTTP/1.1

###
GET http://localhost:3000/products/89a68cdf-3547-43da-b219-3714f4348ef3 HTTP/1.1


###
PUT http://localhost:3000/products/89a68cdf-3547-43da-b219-3714f4348ef3 HTTP/1.1
content-type: application/json

{
  "name": "Arroz do bom",
  "description": "Arroz Camil 1kg",
  "price": 21.00,
  "purchasePrice": 17.25,
  "amount": 4
}

###
DELETE http://localhost:3000/products/79559299-1b45-4a20-a975-361cc60b0664 HTTP/1.1
